<a href="https://colab.research.google.com/github/Tsanyonee/Python/blob/main/10_to_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
baseball =[[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

import numpy as np

np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball.shape)


<class 'numpy.ndarray'>
(4, 2)


In [3]:
baseball = [[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209], [71, 200], [76, 231], [71, 180], [73, 188], [73, 180], [74, 185], [74, 160], [69, 180], [70, 185], [73, 189], [75, 185], [78, 219], [79, 230], [76, 205], [74, 230], [76, 195], [72, 180], [71, 192], [75, 225], [77, 203], [74, 195], [73, 182], [74, 188], [78, 200], [73, 180], [75, 200], [73, 200], [75, 245], [75, 240], [74, 215], [69, 185], [71, 175], [74, 199], [73, 200], [73, 215], [76, 200], [74, 205], [74, 206], [70, 186], [72, 188]]
import numpy as np
np_baseball = np.array(baseball)
print(np_baseball.shape)

(47, 2)


In [6]:
x = [["a", "b", "x"], ["c", "d", "y"], ["e", "f", "z"]]
print([x[0][0], x[1][0], x[2][0]])
import numpy as np
np_x = np.array(x)
print(np_x[:,0])

print(np_x[-2: , :2])

['a', 'c', 'e']
['a' 'c' 'e']
[['c' 'd']
 ['e' 'f']]


In [9]:
baseball = [[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209], [71, 200], [76, 231], [71, 180], [73, 188], [73, 180], [74, 185], [74, 160], [69, 180], [70, 185], [73, 189], [75, 185], [78, 219], [79, 230], [76, 205], [74, 230], [76, 195], [72, 180], [71, 192]]
import numpy as np
np_baseball = np.array(baseball)
print(np_baseball[19,:])

np_weight = np_baseball[: , 1]

print(np_baseball[:,0][24])


[ 79 230]
71


In [10]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print("\n")
print(np_mat + np.array([10, 10]))
print("\n")
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]


[[11 12]
 [13 14]
 [15 16]]


[[ 2  4]
 [ 6  8]
 [10 12]]


In [20]:
"this is getting ridiculous"
import numpy as np
baseball = [[74.0, 180.0, 22.99], [74.0, 215.0, 34.69], [72.0, 210.0, 30.78], [72.0, 210.0, 35.43], [73.0, 188.0, 35.71], [69.0, 176.0, 29.39], [69.0, 209.0, 30.77], [71.0, 200.0, 35.07], [76.0, 231.0, 30.19], [71.0, 180.0, 27.05], [73.0, 188.0, 23.88], [73.0, 180.0, 26.96], [74.0, 185.0, 23.29], [74.0, 160.0, 26.11], [69.0, 180.0, 27.55], [70.0, 185.0, 34.27], [73.0, 189.0, 27.99], [75.0, 185.0, 22.38], [78.0, 219.0, 22.89], [79.0, 230.0, 25.76], [76.0, 205.0, 36.33], [74.0, 230.0, 31.17], [76.0, 195.0, 32.31], [72.0, 180.0, 31.03], [71.0, 192.0, 29.26], [75.0, 225.0, 29.47], [77.0, 203.0, 32.46]]
update = np.array([[1.23035590e+00, -1.11622490e+01,  1.00000000e+00],  [1.02614252e+00,  1.60973231e+01,  1.00000000e+00],  [1.15442280e+00,  5.08167641e+00,  1.00000000e+00],  [6.44275321e-01, -5.09538071e+00,  1.00000000e+00],  [1.00590086e+00,  2.24342718e+00,  1.00000000e+00],  [9.79535475e-01,  1.21984176e+01,  1.00000000e+00],  [6.28743238e-01,  1.37232422e+01,  1.00000000e+00],  [1.27075194e+00, -8.87946313e+00,  1.00000000e+00],  [4.76559454e-01, -1.08249554e+01,  1.00000000e+00],  [9.16993762e-01, -7.01116249e+00,  1.00000000e+00],  [1.17179326e+00,  1.19946614e+00,  1.00000000e+00],  [1.14509104e+00, -1.20038568e+01,  1.00000000e+00],  [1.20684945e+00, -1.32983065e+01,  1.00000000e+00],  [1.03436155e+00,  3.01324251e+00,  1.00000000e+00],  [8.77474537e-01,  1.05177950e+01,  1.00000000e+00],  [9.81330796e-01, -1.55666485e+00,  1.00000000e+00],  [1.03051228e+00,  4.47971582e+00,  1.00000000e+00],  [1.21042271e+00, -1.90450274e+01,  1.00000000e+00],  [1.34612414e+00,  6.74418894e+00,  1.00000000e+00],  [9.75447264e-01,  7.27211497e+00,  1.00000000e+00],  [8.47118513e-01,  2.28271492e-02,  1.00000000e+00],  [8.26148637e-01,  4.64024712e+00,  1.00000000e+00],  [5.53648712e-01, -2.94317618e+00,  1.00000000e+00],  [7.55670499e-01,  1.11495499e+01,  1.00000000e+00],  [9.85196660e-01, -2.56945239e+01,  1.00000000e+00],  [8.62126373e-01,  2.01882766e+00,  1.00000000e+00],  [7.19775782e-01,  1.48238842e+01,  1.00000000e+00]])
np_baseball = np.array(baseball)

print(np_baseball + update)
conversion = np.array([0.0254, 0.453592, 1])
print(np_baseball * conversion)

[[ 75.2303559  168.837751    23.99      ]
 [ 75.02614252 231.0973231   35.69      ]
 [ 73.1544228  215.08167641  31.78      ]
 [ 72.64427532 204.90461929  36.43      ]
 [ 74.00590086 190.24342718  36.71      ]
 [ 69.97953548 188.1984176   30.39      ]
 [ 69.62874324 222.7232422   31.77      ]
 [ 72.27075194 191.12053687  36.07      ]
 [ 76.47655945 220.1750446   31.19      ]
 [ 71.91699376 172.98883751  28.05      ]
 [ 74.17179326 189.19946614  24.88      ]
 [ 74.14509104 167.9961432   27.96      ]
 [ 75.20684945 171.7016935   24.29      ]
 [ 75.03436155 163.01324251  27.11      ]
 [ 69.87747454 190.517795    28.55      ]
 [ 70.9813308  183.44333515  35.27      ]
 [ 74.03051228 193.47971582  28.99      ]
 [ 76.21042271 165.9549726   23.38      ]
 [ 79.34612414 225.74418894  23.89      ]
 [ 79.97544726 237.27211497  26.76      ]
 [ 76.84711851 205.02282715  37.33      ]
 [ 74.82614864 234.64024712  32.17      ]
 [ 76.55364871 192.05682382  33.31      ]
 [ 72.7556705  191.1495499   32.03