<a href="https://colab.research.google.com/github/Tsanyonee/Python/blob/main/6%2C3_to_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50 ]
extra = [ 76, 85]

full = first + second + extra

full_sorted = sorted(full, reverse=True)

print(full_sorted)


[85, 76, 20.0, 18.0, 11.25, 10.75, 9.5]


In [6]:
room = "glasshouse"
room_up = room.upper()
print(room, room_up)

print(len(room))

glasshouse GLASSHOUSE
10


In [8]:
areas = [11.5, 12.8, 20.0, 18.3, 9.50]
print(areas.index(20))
print(areas.count(14.5))

2
0


In [11]:
areas = [10.5, 22, 20.0, 11.5, 9.76]

areas.append(22.5)
areas.append(15.5)
print(areas)

areas.reverse()
print(areas)

[10.5, 22, 20.0, 11.5, 9.76, 22.5, 15.5]
[15.5, 22.5, 9.76, 11.5, 20.0, 22, 10.5]


In [14]:
import numpy
arr = numpy.array([1, 2, 3])
print(arr)

[1 2 3]


In [15]:
import numpy as np
arrg = np.array([1, 2, 3])
print(arrg)

[1 2 3]


In [21]:
r = 0.43
import math
C = 2 * math.pi * r
S = math.pi * r **2
print("Chu_vi: " + str(C))
print("Dien_tich: " + str(S))

Chu_vi: 2.701769682087222
Dien_tich: 0.5808804816487527


In [22]:
r = 192500
from math import radians
dist = radians(12) * r
print(dist)

40317.10572106901


In [23]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

D = A + B
print(D)


[5 7 9]


In [26]:
paintballs = [180, 210, 215, 169, 188, 276, 200]
import numpy as np

np_paintballs = np.array(paintballs)
print(type(np_paintballs))

<class 'numpy.ndarray'>


'would be cool'

In [29]:
"i aint typing all that"
height = [72, 74, 76, 75, 74, 71, 69, 67, 67, 67, 67, 52, 85, 133, 82, 76, 78, 55, 72, 74, 76, 57, 89, 76.2, 45]
import numpy as np
np_height = np.array(height)
print(np_height)

np_height_m = np_height * 0.0254
print(np_height_m)

[ 72.   74.   76.   75.   74.   71.   69.   67.   67.   67.   67.   52.
  85.  133.   82.   76.   78.   55.   72.   74.   76.   57.   89.   76.2
  45. ]
[1.8288  1.8796  1.9304  1.905   1.8796  1.8034  1.7526  1.7018  1.7018
 1.7018  1.7018  1.3208  2.159   3.3782  2.0828  1.9304  1.9812  1.397
 1.8288  1.8796  1.9304  1.4478  2.2606  1.93548 1.143  ]


In [36]:
height = [74, 74, 57, 76, 83, 27, 66, 82, 70, 76, 78 ,72, 74, 77, 73, 84, 76, 83, 88, 105, 76, 83, 47, 75]
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 200, 166, 189, 185, 219, 230, 205, 230]

import numpy as nopls

np_height_m = nopls.array(height) * 0.0254
np_weight_kg = nopls.array(weight) * 0.453592

bmi = np_weight_kg / (np_height_m ** 2)
print(bmi)

[ 23.11037639  27.60406069  45.44305672  25.56171941  19.18667051
 169.73956801  33.73310888  20.91222505  33.14468172  21.91004521
  21.72534076  24.41211827  23.75233129  18.97302091  23.7478741
  18.43364033  24.34449467  16.94142183  17.15909635  11.79752981
  26.65722167  23.47305435  65.24633149  28.74771047]


In [42]:
height = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74]
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215]
import numpy as np
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

light = bmi<21
print(light)
print(bmi[light])

[False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False]
[20.54255679]


In [50]:
height = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73]
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188]

import numpy as np
np_weight = np.array(weight)
np_height = np.array(height)

print(np_weight[17])
print(np_height[10:20])

185
[73 73 74 74 69 70 73 75 78 79]
